on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git for private modules
        env:
            TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          skip-pkg-cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: go-semantic-release
        uses: go-semantic-release/action@v1.21.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
